$(document).ready(function() {
    var owl = $('.owl-carousel');
      owl.owlCarousel({
          items:4,
          loop:true,
          margin:0,
          autoplay:true,
          autoplayTimeout:2000,
          autoplayHoverPause:true,
          responsiveClass:true,
          responsive:{
              0:{
                  items:1,
                  nav:true
              },
              600:{
                  items:2,
                  nav:true
              },
              1000:{
                  items:4,
                  nav:true,
              }
          }
      });
      var owl2 = $('.carousel-part');
      owl2.owlCarousel({
          items:4,
          loop:true,
          margin:60,
          autoplay:true,
          autoplayTimeout:2000,
          autoplayHoverPause:true,
          responsiveClass:true,
          responsive:{
              0:{
                  items:1,
                  nav:true
              },
              600:{
                  items:2,
                  nav:true
              },
              1000:{
                  items:4,
                  nav:true,
              }
          }
      });
      var owl2 = $('.carousel-conf');
      owl2.owlCarousel({
          rtl:true,
          items:4,
          loop:true,
          margin:60,
          autoplay:true,
          autoplayTimeout:2000,
          autoplayHoverPause:true,
          responsiveClass:true,
          responsive:{
              0:{
                  items:1,
                  nav:true
              },
              600:{
                  items:4,
                  nav:true
              },
              1000:{
                  items:4,
                  nav:true,
              }
          }
      });
    
});